# Generated by Django 4.0.5 on 2022-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='abc', max_length=1000),
            preserve_default=False,
        ),
    ]
